oar/cli/cmd_create_test_report.py
oar/cli/cmd_group.py
oar/cli/cmd_take_ownership.py
oar/core/advisory_mgr.py
oar/core/config_store.py
oar/core/const.py
oar/core/jira_mgr.py
oar/core/worksheet_mgr.py
tests/test_advisory_mgr.py
tests/test_jira_mgr.py

add cmd implementation of `take-ownership`
- init config store
- get existing test report
- update task status to `In Progress` in test report
- get subtasks of jira story created by art team
- filter out QE subtasks
- get owner email from cmd option, if it is not set,  get it from config store
- update assignee of QE subtasks
- get all advisories
- check errata state of the advisory. if it is not `QE` log a warning message
- update qe email of advisories to owner email
- update task status to `Pass` in test report
cmd help
```
./cli -r 4.12.11 take-ownership -h
Usage: cli take-ownership [OPTIONS]
Take ownership for advisory and jira subtasks
Options:
-e, --email TEXT  email address of the owner, if option is not set, will use
default owner setting instead
-h, --help        Show this …
```

add cmd take-ownership

---

oar/cli/cmd_check_greenwave_cvp_tests.py
oar/cli/cmd_group.py
oar/core/advisory_mgr.py
oar/core/const.py
tests/test_advisory_mgr.py

Add command `check-greenwave-cvp-test` to check Greenwave CVP test result for all advisories
- command help
```
oar -r 4.12.19 -v check-greenwave-cvp-tests -h
Usage: oar check-greenwave-cvp-tests [OPTIONS]
Check Greenwave CVP test results for all advisories
Options:
```
- command output 
```
oar -r 4.12.19 check-greenwave-cvp-tests
2023-05-26T13:23:34Z: INFO: task [Greenwave CVP testing] status is changed to [In Progress]
2023-05-26T13:24:31Z: INFO: checking Greenwave CVP test for advisory 114720 ...
2023-05-26T13:24:35Z: INFO: Greenwave CVP tests in advisory 114720 are all passed
2023-05-26T13:24:35Z: INFO: checking Greenwave CVP test for advisory 114719 ...
2023-05-26T13:24:39Z: INFO: Greenwave CVP tests in advisory 114719 are all passed …
```

add cmd check-greenwave-cvp-test

---

oar/cli/cmd_drop_bugs.py
oar/cli/cmd_group.py
oar/core/advisory_mgr.py
oar/core/worksheet_mgr.py
tests/test_advisory_mgr.py

- add command `drop-bugs`
- command help
```
oar -r 4.12.19 drop-bugs -h
Usage: oar drop-bugs [OPTIONS]
Drop bugs from advisories
Options:
```
- command output
```
oar -r 4.12.19 drop-bugs
2023-05-31T12:35:03Z: INFO: task [Remove unverified ON_QA bugs] status is changed to [In Progress]
2023-05-31T12:35:59Z: INFO: there is no bug in advisory 114720 can be dropped
2023-05-31T12:36:13Z: INFO: there is no bug in advisory 114719 can be dropped
2023-05-31T12:36:14Z: INFO: there is no bug in advisory 114721 can be dropped
2023-05-31T12:36:15Z: INFO: there is no bug in advisory 114718 can be dropped
2023-05-31T12:36:16Z: INFO: there is no bug in advisory 114722 can be dropped
2023-05-31T12:36:17Z: INFO: task [Remove unverified ON_QA bugs] status is changed …
```

add cmd drop_bugs implementation

---

oar/cli/cmd_take_ownership.py
oar/core/advisory_mgr.py
oar/core/config_store.json
oar/core/jira_mgr.py
oar/core/notification_mgr.py
oar/core/util.py
oar/core/worksheet_mgr.py

- add func `share_ownership_change_result` in message helper to manipulate message for ownership change
- return `updated_ads`,`updated_subtasks`,`abormal_ads` from advisory and jira manager
- call func `share_ownership_change_result` in cmd `take-ownership` to send out slack message
- command output
```
oar -r 4.13.2 take-ownership --email wewang@redhat.com
2023-06-02T13:20:15Z: INFO: task [Take ownership of advisories] status is changed to [In Progress]
2023-06-02T13:20:18Z: INFO: found subtask ART-6939 - release blocker indicator
2023-06-02T13:20:19Z: INFO: found subtask ART-6940 - [Wed] Prepare the release
2023-06-02T13:20:19Z: INFO: found subtask ART-6941 - [Wed-Fri] QE does release verification
2023-06-02T13:20:20Z: INFO: found subtask ART-6942 - [Wed] Promote the tested nightly to …
```

add notification support for cmd take-ownership

---

oar/cli/cmd_take_ownership.py
oar/cli/cmd_update_bug_list.py
oar/core/notification_mgr.py

- add func `get_slack_message_for_bug_verification` in message helper to generate slack message
- send notification in cmd impl `update-bug-list`
- command output
```
oar -r 4.13.2 update-bug-list
2023-06-02T15:54:00Z: INFO: task [Bug to be verified] status is changed to [In Progress]
2023-06-02T15:55:03Z: INFO: found existing bug OCPBUGS-4388 in report, checking...
2023-06-02T15:55:03Z: INFO: bug status of OCPBUGS-4388 is not changed
2023-06-02T15:55:04Z: INFO: found existing bug OCPBUGS-646 in report, checking...
2023-06-02T15:55:05Z: INFO: bug status of OCPBUGS-646 is not changed
2023-06-02T15:55:06Z: INFO: found existing bug OCPBUGS-13480 in report, checking...
2023-06-02T15:55:06Z: INFO: bug status of OCPBUGS-13480 is not changed
2023-06-02T15:55:07Z: INFO: found existing bug …
```

add notification support for cmd update-bug-list

---

prow/README.md
prow/job/job.py

Test
```console
MacBook-Pro:~ jianzhang$ job run periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-gcp-upi-private-xpn-ingress-glb-p2-f14 --payload  quay.io/openshift-release-dev/ocp-release:4.11.0-assembly.art6883.3
Returned job id: 8f0fa25f-4109-4e31-9102-a9cc945680f5
periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-gcp-upi-private-xpn-ingress-glb-p2-f14 quay.io/openshift-release-dev/ocp-release:4.11.0-assembly.art6883.3 8f0fa25f-4109-4e31-9102-a9cc945680f5 2023-06-07T08:11:34Z https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-gcp-upi-private-xpn-ingress-glb-p2-f14/1666357216782848000
MacBook-Pro:~ jianzhang$ …
```

save result to /tmp folder

---

oar/cli/cmd_check_cve_tracker_bug.py
oar/cli/cmd_group.py
oar/core/advisory_mgr.py
oar/core/notification_mgr.py
tests/test_advisory_mgr.py

- call `elliott` cmd to check if there is any new cve tracker bug found
- send slack notification to art team if new tracker bug found
- command help
```
oar -r 4.12.11 check-cve-tracker-bug -h
Usage: oar check-cve-tracker-bug [OPTIONS]
Check if there is any missed CVE tracker bug
Options:
```
- command output
```
oar -r 4.13.2 check-cve-tracker-bug
2023-06-08T13:37:57Z: INFO: task [Check CVE tracker bugs] status is changed to [In Progress]
2023-06-08T13:39:06Z: INFO: found not attached CVE tracker bug
2023-06-08T13:39:06Z: INFO: OCPBUGS-13486: CVE-2023-24540 skopeo: golang: html/template: improper handl
2023-06-08T13:39:06Z: INFO: OCPBUGS-13480: CVE-2023-24540 podman: golang: html/template: improper handl
2023-06-08T13:39:06Z: INFO: OCPBUGS-13474: …
```

add impl of cmd check-cve-tracker-bug

---

oar/cli/cmd_stage_testing.py
oar/core/util.py

about "ERROR: handle_other(): Mutual authentication failed", it's python jenkins related bug, the bug is still new: [bugs.launchpad.net/python-jenkins/+bug/1849302](https://bugs.launchpad.net/python-jenkins/+bug/1849302), it just give the error info, not affect connect to jenkins.
but we avoid display the info.
[wewang@ovpn-12-28 release-tests]$ python cli -r 4.13.2 stage-testing
2023-06-15T15:21:51Z: INFO: job id is not set, will trigger stage testing
2023-06-15T15:22:00Z: INFO: triggerred stage pipeline job: <https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/zstreams/job/Stage-Pipeline/740>
2023-06-15T15:22:01Z: INFO: sent slack message to <#release-tests>
2023-06-15T15:22:03Z: INFO: task [Stage testing] status is changed to [In Progress]
@rioliu-rh  please …

avoid jenkins util error info

---

_releases/required-jobs.json
prow/job/job.py

- Use the `record` branch instead of the `master` branch since the `master` branch is a protection branch.
```console
getting the latest payload of 4.12.0
The latest version of 4.12 is: 4.12.22
file https://api.github.com/repos/openshift/release-tests/contents/_releases/Auto-OCP-4.12.txt doesn't exist, create it.
409 Conflict
use file: _releases/required-jobs.json
```
- Update jobs

fix 409 conflict and update jobs

---

prow/job/job.py

Fix the below issue
```console
The latest version of 4.11 is: 4.11.44
file https://api.github.com/repos/openshift/release-tests/contents/_releases/Auto-OCP-4.11.txt doesn't exist, create it.
422 Unprocessable Entity
use file: _releases/required-jobs.json
4.11.
```

use the record branch instead of master

---

prow/job/__init__.py
prow/job/job.py

There are 4 Envs for OCP payload, 
```console
"RELEASE_IMAGE_LATEST"
"RELEASE_IMAGE_TARGET"
"RELEASE_IMAGE_ARM64_LATEST"
"RELEASE_IMAGE_ARM64_TARGET"
```
But, for ARM jobs, we have to set the `RELEASE_IMAGE_LATEST`(x86) when using the API call since it contains the `cli` image. Otherwise, you will get the error below, such as https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-arm64-stable-baremetalds-ipi-ovn-ipv4-p2-f14/1675773761678217216 
A DPTP issue: https://issues.redhat.com/browse/DPTP-3538
```console
ERRO[2023-07-03T07:51:10Z] 
* could not run steps: step [release:latest] failed: failed to get CLI image: unable to find the 'cli' image in the provided release image: could not watch pod: …
```

Fix issues for ARM

---

prow/job/job.py

if the job name is incorrect, it only can be checked in resp headers
```
job --debug run periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-openshift-logging-5.7-aws-ipi-proxy-sdn-workers-rhel8-p1-f7 --payload registry.ci.openshift.org/ocp/release:4.13.0-0.nightly-2023-07-05-213721
Debug mode is on
{'job_execution_type': '1', 'pod_spec_options': {'envs': {'RELEASE_IMAGE_LATEST': 'registry.ci.openshift.org/ocp/release:4.13.0-0.nightly-2023-07-05-213721'}}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gangway-ci.apps.ci.l2s4.p1.openshiftapps.com:443
send: b'CONNECT gangway-ci.apps.ci.l2s4.p1.openshiftapps.com:443 HTTP/1.0\r\n\r\n'
send: b'POST /v1/executions/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-openshift-logging-5.7 …
```

add http level debug logging

---

oar/core/worksheet_mgr.py

```
oar -r 4.12.25 create-test-report
^@^@^@^@^@^@^@^@^@2023-07-20T12:30:47Z: ERROR: create new test report failed  Traceback (most recent call last):
File "/Users/rio.liu/coderepo/release-tests/oar/cli/cmd_create_test_report.py", line 21, in create_test_report
report = wm.create_test_report()
^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rio.liu/coderepo/release-tests/oar/core/worksheet_mgr.py", line 67, in create_test_report
raise WorksheetException(
oar.core.exceptions.WorksheetException: test report of 4.12.25 exists, url: https://docs.google.com/spreadsheets/d/1NNIzctvTC6zhYD7nFyFSgrJ3E8CF5qCU8iJbDhZyzAM#gid=1115454007
File "/usr/local/bin/oar", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/rio.liu/coderepo/release-tests/oar/cli/__main__.py", line …
```

raise error if test report already exists

---

oar/core/advisory_mgr.py

issue:
2023-07-21T18:54:21Z: INFO: checking push job status for advisory 117560 ...
File "/home/wewang/522/release-tests/oar/core/advisory_mgr.py", line 148, in push_to_cdn_staging
ad.push_to_cdn()
TypeError: Advisory.push_to_cdn() missing 1 required positional argument: 'target'
The above exception was the direct cause of the following exception:
fixed result:
2023-07-21T18:59:14Z: INFO: checking push job status for advisory 117560 ...
File "/home/wewang/522/release-tests/oar/core/advisory_mgr.py", line 148, in push_to_cdn_staging
ad.push_to_cdn("")
File "/home/wewang/522/release-tests/oar/core/advisory_mgr.py", line 354, in push_to_cdn
self.push()
File "/home/wewang/.local/lib/python3.10/site-packages/errata_tool/errat …

fix push-to-cdn-staging issue

---

Makefile

As title, but `oar -h` fail to run, @rioliu-rh do you happen to know why?
```console
MacBook-Pro:release-tests jianzhang$ make install
python3 -m pip install --upgrade pip && pip3 install -e . && oar -h
...
Successfully installed oar-0.1.dev108+ge88dabe
File "/opt/homebrew/bin/oar", line 5, in <module>
from oar.cli.__main__ import main
ImportError: cannot import name 'main' from 'oar.cli.__main__' (/opt/homebrew/lib/python3.11/site-packages/release_tests-1.0.0-py3.11.egg/oar/cli/__main__.py)
make: *** [install] Error 1
MacBook-Pro:release-tests jianzhang$ oar -h
File "/opt/homebrew/bin/oar", line 5, in <module>
from oar.cli.__main__ import main
ImportError: cannot import name 'main' from 'oar.cli.__main__' …
```

add installation test

---

oar/core/worksheet_mgr.py

and add waiting info for generate bugs in sheet, because sometimes it's not very fast, when there are many bugs

Add full url for ad in sheet

---

_releases/required-jobs.json

As title, updates based on https://github.com/openshift/release/tree/master/ci-operator/jobs/openshift/openshift-tests-private

add required jobs for 4.9

---

oar/cli/cmd_group.py
oar/core/config_store.py

@rioliu-rh  please check it, thanks
when create 4.13.7 report, which errata is not ready, 
original output is:
$oar -r 4.13.7 create-test-report
'4.13.7'
so fixed it, when errata is not ready, should give info about the reason, 
fixed output:
$oar -r 4.13.7 create-test-report
2023-07-27T13:11:58Z: ERROR: config store initialization failed
File "/home/wewang/522/release-tests/oar/cli/cmd_group.py", line 46, in cli
ConfigStore(release)
File "/home/wewang/522/release-tests/oar/core/config_store.py", line 58, in __init__
raise ConfigStoreException(f"[{self.release}] advisories are not ready, cannot create test report,you can check:{url}")
oar.core.exceptions.ConfigStoreException: [4.13.7] advisories are not ready, cannot create test report,you can …

Fix issue for create test report when errata is not ready

---

oar/README.md
oar/core/notification_mgr.py

```console
10. This command will check all the not verified bugs from advisories, if any bug is `Critical` or `CVE Tracker` or `Customer Case` it is must-verify bug, need to confirm with bug owner, slack notification will be sent out. the rest of the bugs will be dropped automatically
```

refine notification message for must verify bug

---

oar/cli/cmd_group.py

enhancement: don't initialize config store (download ocp data from remote) if the command has help option
```console
oar -r 4.12.25 check-greenwave-cvp-tests -h
Usage: oar check-greenwave-cvp-tests [OPTIONS]
Check Greenwave CVP test results for all advisories
Options:
oar -r 4.12.25 check-greenwave-cvp-tests --help
Usage: oar check-greenwave-cvp-tests [OPTIONS]
Check Greenwave CVP test results for all advisories
Options:
```

don't initialize config store with help option

---

prow/Dockerfile.k8sgpt

Address this failure: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/42096/rehearse-42096-periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-alibaba-ipi-private-fips-f28/1689506642434985984
```console
INFO[2023-08-10T06:17:13Z] /bin/bash: line 11: k8sgpt: command not found
```

update k8sgtp dockerfile

---

oar/cli/cmd_take_ownership.py
oar/core/config_store.json

- make email as required option for cmd take-ownership
- reformat config_store.json
```console
Usage: oar take-ownership [OPTIONS]
Take ownership for advisory and jira subtasks
Options:
-e, --email TEXT  email address of the owner  [required]
-h, --help        Show this message and exit.
```

make email as required option for cmd take-ownership

---

oar/core/advisory_mgr.py
oar/core/const.py

per discussion with ART team, microshift advisory will be processed separately. when it is in NEW_FILES state, we can kick off verification test process. made this change to exclude this kind of advisory from abnormal advisory check logic

exclude microshift advisory check

---

oar/core/worksheet_mgr.py
tests/test_worksheet_mgr.py

use new client `gspread.client.BackoffClient` to initialize gspread service, fix google sheet request quota limit issue. the new client has impl of with exponential backoff retries
ref: https://docs.gspread.org/en/v5.8.0/api/client.html#gspread.client.BackoffClient
```console
./test_worksheet_mgr.py::TestWorksheetManager::test_report Passed
Total number of tests expected to run: 1
Total number of tests run: 1
Total number of tests passed: 1
Total number of tests failed: 0
Total number of tests failed with errors: 0
Total number of tests skipped: 0
Finished running tests!
```

fix google sheet request quota limit issue

---

oar/core/advisory_mgr.py

if we want to change advisory state to `REL_PREP`, validate current state of advisory, if it is not `QE`, skip the operation for this advisory

validate advisory current state and target state

---

oar/cli/cmd_image_consistency_check.py
oar/core/config_store.py
oar/core/jenkins_helper.py

if no -c option , default using stable build to test:
$oar -r 4.12.28 image-consistency-check
if -c option, use nightly build to test:
$oar -r 4.12.28 image-consistency-check -c
if has -n option and -c option, will give error info:

[OCPQE-16445]support nightly build for image consistency check job

---

prow/Dockerfile.k8sgpt

Since https://github.com/k8sgpt-ai/k8sgpt/issues/604 issue has been addressed(https://github.com/k8sgpt-ai/k8sgpt/blob/main/pkg/kubernetes/kubernetes.go#L40), use the official repo instead of mine.
```console
[cloud-user@preserve-olm-env2 prow]$ podman --runtime crun build -f Dockerfile.k8sgpt -t quay.io/olmqe/k8sgpt:vv1 .
STEP 1/6: FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14
STEP 2/6: LABEL maintainer="jiazha@redhat.com"
--> Using cache 3e652b1d507977befd63bd35de6d12498bca3a06f3a9fec70c4aac567bbf0f90
--> 3e652b1d5079
STEP 3/6: WORKDIR /go/src/github.com/k8sgpt-ai
--> Using cache 6efa777f86de14b2de59224ebc13a69d8393fa76951226aeed82e2f10c08c315
--> 6efa777f86de
STEP 4/6: RUN git clone --branch main https://github.com/k8sgpt-ai/k8sgpt.git &&     cd k8sgpt && …
```

use k8sgpt official repo instead of personal's

---

oar/core/jenkins_helper.py

fix issue like below
```console
2023-10-09T21:35:59Z: INFO: job id is not set, will trigger stage testing
2023-10-09T21:36:00Z: ERROR: trigger stage testing failed
File "/home/cloud-user/release-tests/oar/cli/cmd_stage_testing.py", line 44, in stage_testing
build_url = jh.call_stage_job()
^^^^^^^^^^^^^^^^^^^
File "/home/cloud-user/release-tests/oar/core/jenkins_helper.py", line 31, in call_stage_job
build_url = self.call_build_job(JENKINS_JOB_STAGE_PIPELINE)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: JenkinsHelper.call_build_job() missing 1 required positional argument: 'pull_spec'
```
with the fix
```cosnole
$ oar -r 4.13.15 stage-testing
^@^@^@^@^@^@^@^@^@^@2023-10-10T10:09:46Z: INFO: job id is not set, will trigger stage testing …
```

add missed argument for call stage pipeline job

---

oar/core/advisory_mgr.py
tests/test_advisory_mgr.py

for push to cdn staging job, we need to checkout advisory dependencies. trigger push job for dependent advisories first.
- add func `has_dependency` to check whether there is any dependent advisory
- add func `get_dependent_advisories` to get dependent advisory list
- refine func `push_to_cdn`, move func `are_all_push_jobs_completed` into this func, return boolean flag to indicate whether job is triggered or not
add unit test for this logic
```console
Running tests: release-tests/tests/test_advisory_mgr.py::TestAdvisoryManager::test_get_dependent_advisories
./test_advisory_mgr.py::TestAdvisoryManager::test_get_dependent_advisories Passed
Total number of tests expected to run: 1
Total number of tests run: 1
Total number of tests passed: 1
Total number of tests failed: 0
Total number of …
```

OCPQE-17313 add func to check dependent advisories

---

prow/job/__init__.py
prow/job/job.py

As title, test
```console
MacBook-Pro:release-tests jianzhang$ job run --payload quay.io/openshift-release-dev/ocp-release:4.14.0-multi periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-amd-mixarch-f28
{'job_execution_type': '1', 'pod_spec_options': {'envs': {'RELEASE_IMAGE_MULTI_LATEST': 'quay.io/openshift-release-dev/ocp-release:4.14.0-multi'}}}
Returned job id: 7d5ab5bb-c64a-4229-b326-019621c18580
periodic-ci-openshift-openshift-tests-private-release-4.14-multi-nightly-azure-ipi-amd-mixarch-f28 quay.io/openshift-release-dev/ocp-release:4.14.0-multi 7d5ab5bb-c64a-4229-b326-019621c18580 2023-10-30T03:54:55Z https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-priva …
```

OCPQE-17601: add supports for ppc64le, multi platforms

---

oar/core/config_store.py
tests/test_config_store.py

https://issues.redhat.com/browse/OCPQE-17717
in latest ocp build data e.g. https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.14/releases.yml, new attribute names are introduced i.e. suffixed with symbol ! e.g. advisories!
xref: https://art-docs.engineering.redhat.com/assemblies/#inheritance-rules
for most important attributes: advisories, release_jira, refenrence_releases, we need to check whether the attribute with suffix ! exists, if yes, get its value for current release, if not, get unsuffixed attribute value, otherwise, get the same attribute value from parent release.

OCPQE-17717 support inheritance rule when parsing ocp build data

---

oar/core/config_store.py
oar/core/notification_mgr.py

this issue is introduced by [OCPQE-17717](https://issues.redhat.com/browse/OCPQE-17717), in 4.12 build data, it does not have parent assembly defined. so no inherited assembly. in OAR CLI code, we need to add this json key check, thanks for reporting this

OCPQE-17759 fix get advisory issue on 4.12

---

pyproject.toml

- install pkg pip-system-certs to replace ssl cert management pkg certifi. we will use system default trust ca bundle for SSL certification
- update rh-elliott pkg url due to ART team moved all the tools to new repo

OCPQE-17982 update pkg dependency

---

oar/cli/cmd_push_to_cdn.py
oar/core/advisory_mgr.py

- previous PR https://github.com/openshift/release-tests/pull/102 does not have the correct fix.
- get AD dependency with errata attribute `blocking_advisories`, not `dependent_advisories`
- cache the push job info, avoid to call this api frequently
- add helper functions to check push job state, e.g. `are_push_jobs_running`, `are_push_jobs_completed` and `has_failed_push_job`
- if one AD has blocking ADs, trigger pub job for them anyway. then check the job state, if any of them is not completed, log warn message to ask user try again later, because only push jobs of  blocking ADs are all completed, then we can trigger push job for current AD. 
- if all push jobs are triggered for all the ADs, mark the task status in report to pass
- to trigger push to CDN jobs for all the ADs, we need to …

OCPQE-17313 fix blocking advisory issue

---

oar/cli/cmd_push_to_cdn.py
oar/core/advisory_mgr.py

refine the logic of func `Advisory.push_to_cdn`, true means all jobs are completed. false means jobs are running or just triggered
- if all push jobs are completed, return true
- if any push job is running and there is no failed job, return false. i.e. action is in progress
- if no jobs are triggered or there is any failed job found (retry), trigger the push job with target [stage]
- if any blocking advisory found, trigger push job for it
- if all the blocking jobs are completed, trigger push job for current advisory
/assign @ming1013

OCPQE-18416 refine logic of push to cdn staging

---

prow/job/__init__.py
prow/job/job.py

Before, the job infer the amd64 image is `quay.io/openshift-release-dev/ocp-release:4.15.0-x86_64`, it doesn't exist and lead `  * could not run steps: step [release:latest] failed: unable to import latest release image: timed out waiting for the condition `, details:  https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-4.16-upgrade-from-stable-4.15-azure-ipi-ovn-ipsec-f14/1739485263698071552 
```console
MacBook-Pro:~ jianzhang$ job run periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-4.16-upgrade-from-stable-4.15-azure-ipi-ovn-ipsec-f14 --upgrade_from=quay.io/openshift-release-dev/ocp-release:4.15.0-rc.0-aarch64 …
```

update amd64 base image query for arm payload

---

prow/job/job.py

As title, 
```console
MacBook-Pro:release-tests jianzhang$ job run_z_stream_test
use JSON file: _releases/required-jobs.json
getting the latest payload of 4.10
The latest version of 4.10 is: 4.10.67
Run job: periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-stable-aws-ipi-ovn-fips-p2-f28
Run job: periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-stable-azure-ipi-fips-p2-f28
Run job: periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-stable-gcp-ipi-proxy-private-p2-f28
Run job: periodic-ci-openshift-openshift-tests-private-release-4.10-amd64-stable-vsphere-ipi-proxy-fips-p2-f28
Run job: periodic-ci-openshift-openshift-tests-private-release-4.10-arm64-stable-aws-ipi-ovn-p2-f28
Run job: …
```

add run_z_stream_test command

---

prow/job/job.py

It couldn't get the job results immediately once the job triggered sometimes, 
```console
Run job: periodic-ci-openshift-openshift-tests-private-release-4.9-sanity
{'job_execution_type': '1', 'pod_spec_options': {'envs': {'RELEASE_IMAGE_LATEST': 'quay.io/openshift-release-dev/ocp-release:4.9.59-x86_64'}}}
Returned job id: 22114ef1-411e-41d3-8399-8c5c3fe07eda
Not found the url link or creationTimestamp...
```
But, it did run, so add `1s` sleep.
```console
MacBook-Pro:release-tests jianzhang$ job get_results 22114ef1-411e-41d3-8399-8c5c3fe07eda
None None 22114ef1-411e-41d3-8399-8c5c3fe07eda 2024-01-05T07:07:07Z https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.9-sanity/1743167225 …
```

add 1s sleep for job startup

---

prow/Dockerfile.k8sgpt

Address https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release-tests/128/pull-ci-openshift-release-tests-master-images/1746807193346248704
```console
vendor/github.com/pterm/pterm/slog_handler.go:6:2: package log/slog is not in GOROOT (/usr/lib/golang/src/log/slog)
note: imported by a module that requires go 1.21
make: *** [Makefile:57: build] Error 1
error: build error: building at STEP "RUN git clone --branch main https://github.com/k8sgpt-ai/k8sgpt.git &&     cd k8sgpt &&     go mod vendor &&     make build": while running runtime: exit status 2
```

use go1.21 for k8sgpt

---

prow/job/job.py

Remove the `Exception`.
```python
jiazha-mac:~ jiazha$ job get_results 1747152353489850368
File "/opt/homebrew/bin/job", line 33, in <module>
sys.exit(load_entry_point('job', 'console_scripts', 'job')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1137, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1062, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.12/site-packages/click/core.py", line 1668, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

update error handles

---

prow/job/controller.py

if build is valid and cannot find latest stable build from stream `4-stable` e.g. `4.16`, we check `4-dev-preview` release stream instead.
```console
$ jobctl start-controller -r 4.16 --no-nightly --trigger-prow-job false
2024-02-02T17:48:43Z: INFO: Getting latest stable build for 4.16 ...
2024-02-02T17:48:44Z: INFO: Latest  stable build of 4.16 is:
{
"name": "4.16.0-ec.1",
"phase": "Accepted",
"pullSpec": "quay.io/openshift-release-dev/ocp-release:4.16.0-ec.1-x86_64",
"downloadURL": "https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.16.0-ec.1"
}
2024-02-02T17:48:45Z: INFO: File _releases/ocp-latest-4.16-stable.json not found
2024-02-02T17:48:45Z: INFO: File _releases/ocp-latest-4.16-stable.json not found
2024-02-02T17:48:45Z: INFO: Creating file …
```

OCPQE-19030 support ec build for latest release

---

prow/job/controller.py
prow/job/job.py

- when new build is found job controller will trigger the prow job and save the job name/id on github branch `record` 
```console
$ jobctl start-controller -r 4.16 --nightly
```
- run test result aggregator to scan all the test result files like `_releases/ocp-test-result-$build.json`, check all the prow jobs' state, skip the optional job, if `required-job-count == success-job-count`, update releasepayload, updated test result is like https://github.com/openshift/release-tests/blob/record/_releases/ocp-test-result-4.16.0-0.nightly-2024-02-03-221256.json
```console
$ jobctl start-aggregator
2024-02-04T21:45:33Z: INFO: Initializing test job registry ...
2024-02-04T21:45:35Z: INFO: Test job definitions for 4.16 is initialized
2024-02-04T21:45:35Z: INFO: Test job registry is initialized …
```

OCPQE-19030 test result aggregator and related flow

---

prow/job/controller.py
prow/job/job.py

- if no prow job found from server side, i.e. the prow job is expired. we use updated job info from the test result instead.
- if all the jobs are completed, i.e. the test result was aggregated, insert a attribute `aggregated: true` to test result, and it will be skipped in next sync
- reformat `job.py` by pep8 style
```console
$ jobctl start-aggregator
2024-02-20T14:22:29Z: INFO: Initializing test job registry ...
2024-02-20T14:22:30Z: INFO: Test job definitions for 4.16 is initialized
2024-02-20T14:22:30Z: INFO: Test job registry is initialized
2024-02-20T14:22:31Z: INFO: Start to scan test result files ...
2024-02-20T14:22:32Z: INFO: Found test result file ocp-test-result-4.16.0-0.nightly-2024-02-03-221256.json
2024-02-20T14:22:32Z: INFO: Start to check test result for …
```

OCPQE-19030 fix aggregator issue

---

prow/job/controller.py

- check if nightly build cannot be found no releasestream
- if the nightly cannot be found i.e. it is recycled, skip aggregation and delete test result file
- add some comments in code
```console
$ jobctl --debug start-aggregator
2024-02-22T11:08:22Z: DEBUG: Starting new HTTPS connection (1): api.github.com:443
2024-02-22T11:08:23Z: DEBUG: https://api.github.com:443 "GET /repos/openshift/release-tests HTTP/1.1" 200 None
2024-02-22T11:08:23Z: INFO: Initializing test job registry ...
2024-02-22T11:08:24Z: DEBUG: https://api.github.com:443 "GET /repos/openshift/release-tests/contents/_releases?ref=master HTTP/1.1" 200 None
2024-02-22T11:08:24Z: DEBUG: https://api.github.com:443 "GET /repos/openshift/release-tests/contents/_releases/ocp-4.16-test-jobs.json?ref=master HTTP/1.1" 200 None …
```

OCPQE-19030 skip aggregation and recycle test result if nightly build is recycled.

---

prow/job/controller.py
pyproject.toml

in the old install config `pyproject.toml`, package `gspread` version is not specified. latest version `6.0.x` will be installed. but `6.x` is totally different with `5.x`. 
it is not compatible with current implementation. `spread.client.BackoffClient` does not exist. in new version the params of func `gspread.authorize` is different. 
for temp w/a, we set `gspread` version to `5.10.0`

Update gspread version in install config

---

prow/job/controller.py

- Multi arch support for cli
```console
$ jobctl start-controller --help
Usage: jobctl start-controller [OPTIONS]
Options:
-r, --release TEXT              y-stream release number e.g. 4.15
[required]
--nightly / --no-nightly        run controller for nightly or stable build,
default is nightly
--trigger-prow-job BOOLEAN      trigger prow job if new build is found
--arch [amd64|arm64|multi|ppc64le]
architecture used to filter accepted build
--help                          Show this message and exit.
$ jobctl start-aggregator --help
Usage: jobctl start-aggregator [OPTIONS]
Options:
--arch [amd64|arm64|multi|ppc64le]
architecture used to filter test result
--help                          Show this message and exit.
```
- Add class `ReleaseStreamURLResolver` to get latest build url for …

OCPQE-19629 add multi arch support for job controller and test result aggregator

---

prow/job/sippy.py
tests/test_sippy.py

- query risk analysis with job run id with get request
- query risk analysis with payload json file with get request
- analyze response data to determine whether the job run is risky

OCPQE-20409 Phase II add API support for risk analysis

---

pyproject.toml

the pkg `cryptography` is required for jwe decryption
/assign @ming1013

add jose dependency pkg for decryption

---

prow/job/artifacts.py

make a minor change to get suite name of failed test from root element of junit xml
```
$ py -m unittest test_artifacts.TestArtifacts.test_generate_job_summary
2024-04-15T14:05:27Z: INFO: {
"ID": 1775675266119503872,
"ProwJob": {
"Name": "periodic-ci-openshift-openshift-tests-private-release-4.15-automated-release-aws-ipi-fips-f1"
},
"Tests": [
{
"Test": {
"Name": "OCP-37491:SDN EgressFirewall allows traffic to destination dnsName"
},
"Suite": {
"Name": "Egress-ingress related networking scenarios"
},
"Status": 12
}
],
"TestCount": 256
}
```

OCPQE-20766 add suite name for failed case

---

_releases/ocp-4.16-test-jobs-amd64.json

Select prow jobs for 4.16 nightly/stable from automated release job pool
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__automated-release.yaml
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__automated-release-stable-4.16-upgrade-from-stable-4.16.yaml
/assign @liangxia @jianzhangbjz @jhou1 @chengzhang1016 
Can you review and comment. TODO: enable job controller job when this PR is merged.

OCPQE-22219 add test jobs definition for 4.16 release

---

prow/job/controller.py
prow/job/job.py

Fix error in job https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-tests-master-qe-release-gate-test/1792484273572286464/artifacts/qe-release-gate-test/release-qe-tests/build-log.txt
Solution: sometimes api cannot get job url, but it does not matter for func `run_job`, we just need `job_id`. so exceptions raised from this func can be ignored.

OCPQE-22219 catch error for getting job result

---

_releases/ocp-4.16-test-jobs-amd64.json

According to install failure analysis. azure-stack based automated release job does not have enough capacity to support testing frequency of nightly and stable

OCPQE-22219 disable azure-stack job due to insufficient capacity

---

_releases/ocp-4.16-test-jobs-amd64.json

disable job periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-baremetalds-ipi-ovn-dualstack-primaryv6-f360, there are too many install failures observed.

OCPQE-22219 disable baremetal job due to install failures

---

prow/job/selector.py
tests/test_selector.py

- Add class `AutoReleaseJobs` to get auto release jobs for different releases
- currently only support amd64 jobs
- Unit test results
```console
$ py -m unittest test_selector.TestSelector.test_get_not_supported_release
2024-05-22T15:45:19Z: DEBUG: Starting new HTTPS connection (1): api.github.com:443
2024-05-22T15:45:20Z: DEBUG: https://api.github.com:443 "GET /repos/openshift/release HTTP/1.1" 200 None
2024-05-22T15:45:20Z: DEBUG: https://api.github.com:443 "GET /repos/openshift/release/contents/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__automated-release.yaml?ref=master HTTP/1.1" 404 None
2024-05-22T15:45:20Z: INFO: File ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__automated …
```

OCPQE-22219 add automate release job implementation

---

prow/job/selector.py
prow/setup.py
tests/test_selector.py

Add `TestJobRegistryUpdater` implementation
Components
- GithubApp: use to create pull request and add labels.
- LocalGitRepo: 
- use to clone forked repo
- make local change
- commit and push to remote. (the repo url is got from app installed on my account)
- TestJobRegistryUpdater
- make local change in cloned repo
- create new PR on openshift/release-tests for test job registry files
- add labels to approve the PR
Github App is marked as public and it's transferred to openshift org. Requested to install the app to repo `openshift/release-tests`

OCPQE-21399 add test job registry updater implementation

---

prow/job/controller.py

refine retry logic due to limited quota, default retry num is 2, total job run number is 3, i.e. firstJob+ retriedJobs. acceptance criteria is BO3

OCPQE-19825 refine retry logic

---

_releases/ocp-4.12-test-jobs-amd64.json

According to discussion with installer team [redhat-internal.slack.com/archives/CH76YSYSC/p1718587132710229](https://redhat-internal.slack.com/archives/CH76YSYSC/p1718587132710229)
>  shared-vpc is not officially supported in 4.12
Remove share vpc related auto release job from 4.12 job registry

OCPQE-22653 replace aws vpc job with mini perm job

---

prow/job/controller.py

if current build file does not exist, latest build will be considered as new build, jobs will be triggered

Check current build file exists or not

---

prow/job/controller.py

currently logic is when getting latest build, if record file does not exist, create it on github, the logic is useless
remove this logic, when the file does not exist, i.e. current build not found, so controller will trigger test and create the file accordingly.
```console
$ jobctl start-controller -r 4.13 --nightly --trigger-prow-job false
2024-07-09T08:12:17Z: INFO: Initializing test job registry ...
2024-07-09T08:12:18Z: INFO: Test job definitions for 4.12-amd64 is initialized
2024-07-09T08:12:19Z: INFO: Test job definitions for 4.15-amd64 is initialized
2024-07-09T08:12:19Z: INFO: Test job definitions for 4.16-amd64 is initialized
2024-07-09T08:12:19Z: INFO: Test job registry is initialized
2024-07-09T08:12:22Z: INFO: Getting latest nightly build for 4.13 ...
2024-07-09T08:12:23Z: …
```

remove record file creation when getting latest build

---

oar/cli/cmd_take_ownership.py
oar/core/jira_mgr.py

- user email id to query jira user
- valid email address
```console
$ oar -r 4.12.60 take-ownership -e rioliu
Usage: oar take-ownership [OPTIONS]
Try 'oar take-ownership -h' for help.
Error: Invalid value for '-e' / '--email': rioliu is not a valid email address
```

refine cmd take-ownership

---

prow/job/controller.py

There is a bug about how to determine upgrade path from prow job name 
we only support this logic when upgrade path is from latest patch version of current release, e.g. if the job name contains `upgrade-from-stable-4.16` and the job is used to test nightly build, by default the `release.latest` in job definition is `4.16.(z-1)`, but it should be latest stable `4.16.z`, if the job name contains `upgrade-from-stable-4.15`, it means this job is used to test upgrade b/w minor releases e.g. from 4.15.z to 4.16.z, we should not override the `release.latest`

OCPQE-23403 correct job name check logic

---

oar/cli/cmd_image_signed_check.py

```console
$ oar -v -r 4.12.61 image-signed-check
2024-07-23T18:29:33Z: INFO: task [Payload image is well signed] status is changed to [In Progress]
2024-07-23T18:29:34Z: INFO: Getting digest from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-stable/release/4.12.61
2024-07-23T18:29:37Z: INFO: Image Digest: sha256:faa201ea7790bb101de7b9b6f01543136e8c589463b8437a10678da0cdd0197a
2024-07-23T18:29:37Z: INFO: Comparing digest from url: https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release/sha256=faa201ea7790bb101de7b9b6f01543136e8c589463b8437a10678da0cdd0197a/signature-1
2024-07-23T18:29:38Z: INFO: Signature check PASSED
2024-07-23T18:29:39Z: INFO: task [Payload image is well signed] status is changed to [Pass]
```
slack thread: …

OCPQE-24160  check file signature-1 instead of dir on mirror.openshift.com

---

prow/job/job.py

if payload is nightly build, don't add amd64 build as `RELEASE_IMAGE_LATEST`
e.g. https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.16-arm64-nightly-aws-ipi-private-f28-disasterrecovery/1816453416201752576

OCPQE-24207 don't specify env var RELEASE_IMAGE_LATEST for arm nightly

---

oar/core/advisory_mgr.py
tests/test_advisory_mgr.py

erratum API supports getting secalert for advisory. add new funcs to check whether there is any blocking secalert
```
$ py -m unittest test_advisory_mgr.TestAdvisoryManager.test_get_security_alerts
2024-07-30T15:32:16Z: WARNING: RHBA advisory 136330 does not have secalerts
2024-07-30T15:32:18Z: INFO: RHSA advisory 136331 does not have blocking secalert
2024-07-30T15:32:18Z: WARNING: RHBA advisory 136332 does not have secalerts
2024-07-30T15:32:18Z: WARNING: RHBA advisory 136333 does not have secalerts
.
----------------------------------------------------------------------
Ran 1 test in 60.227s
OK
```

OCPQE-24321 check secalert for RHSA advisory

---

oar/controller/detector.py

if get latest version of z-stream or stable build failed, exit

OCPQE-24474 add error handling logic for release detector

---

oar/controller/detector.py

```
$ oarctl start-release-detector
Please input the minor version of OCP: 4.12
2024-08-12T09:54:21Z: INFO: latest z-stream version: 4.12.62
2024-08-12T09:54:21Z: INFO: latest stable version: 4.12.62
2024-08-12T09:54:21Z: INFO: no new z-stream release found
```

OCPQE-24474 add prompt for detector option

---

prow/job/controller.py

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-tests-master-qe-release-gate-test/1829100491833872384/artifacts/qe-release-gate-test/release-qe-tests/build-log.txt
check if job metadata not found in job registry, if yes, skip aggregation for the job. 
```
2024-08-29T18:50:20Z: INFO: Cannot find test job periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-fips-f4-disasterrecovery in 4.16 definition
2024-08-29T18:50:20Z: INFO: skip aggreation for job run of periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-ipi-private-fips-f4-disasterrecovery
```

Fix job metadata not found issue

---

tools/auto_release_test_dashboard.py

- add webUI tool to list automated-release test results for different minor releases
- by default, release is 4.12
- use can choose other supported release in select box
- test results will be cached, web page load time is a bit longer at the first time
- configure the selection mode of dataframe as single row, when select the row, will show dialog with all prow job links
<pre>
</pre>
<pre>
</pre>
Usage: 
- setup steramlit env 
```
pip install streamlit
```
- export env var
```
export GITHUB_TOKEN=xxx
```
- start server
```
streamlit run auto_release_test_dashboard.py
```

add auto release test result dashboard

---

tools/auto_release_test_dashboard.py

- refine the button label from `Clear Cache` to `Refresh`
- sync test result data from github when click the refresh button
- change symbol for job state `pending` from `WIP` to `P`, so all the state symbols are single char

refine ui components

---

prow/job/controller.py

when trigger upgrade job with nightly, we have an enhancement that use latest stable build as release.latest. but there is a scenario that when job controller is running for nightly at the first time. stable build file is not initialized. so we have to get the latest stable build in runtime.

HOTFIX: fix no stable build issue when trigger upgrade job for nightly

---

oar/README.md
oar/cli/cmd_group.py

when required option is missed, raise error
```console
$ oar update-bug-list
Usage: oar [OPTIONS] COMMAND [ARGS]...
Try 'oar -h' for help.
Error: Missing option. -r/--release is required
```
option release is not required when getting usage of sub-cmd
```console
$ oar update-bug-list -h                                                                                                                                                                                          2 ↵
Usage: oar update-bug-list [OPTIONS]
Update bug status listed in report, update existing bug status and append
new ON_QA bug
Options:
--notify / --no-notify  Send notification to bug owner, default value is
true
-h, --help              Show this message and exit.
```

OCPQE-25622 validate required option implicitly

---

oar/core/jenkins.py

```
$ oar -r 4.12.66 stage-testing
2024-09-17T15:57:21Z: INFO: job id is not set, will trigger stage testing
2024-09-17T15:57:26Z: ERROR: trigger stage pipeline job failed
File "/Users/rio.liu/coderepo/release-tests/oar/core/jenkins.py", line 32, in call_stage_job
raise JenkinsException("metadata advisory not found")
jenkins.JenkinsException: metadata advisory not found
The above exception was the direct cause of the following exception:
File "/Users/rio.liu/coderepo/release-tests/oar/cli/cmd_stage_testing.py", line 44, in stage_testing
build_url = jh.call_stage_job()
^^^^^^^^^^^^^^^^^^^
File "/Users/rio.liu/coderepo/release-tests/oar/core/jenkins.py", line 37, in call_stage_job
raise JenkinsHelperException( …
```

OCPQE-25667 check metadata ad when call stage pipeline job

---

oar/core/jira.py

for y stream release, like 4.17.0 there are hundreds of bugs attached to the advisories. jira manager needs to check them all and filter all the ONQA bugs. but it will hit jira api limit error. now jira will not send status code 429 and corresponding headers for retry. it will send 401 code back to the client. so we need to handle this case in our code, sleep for a while (in this case 1.75 secs) when specific number of jira issues are processed

OCPQE-26054 refine logic for jira api limit handler

---

oar/core/worksheet.py

when iterate bugs in report, if we get 403 error, don't terminate the process. catch the exception and do nothing, i.e. skip the issued bug (it's possible that jira bot does not have permission to access restricted bugs)

handle 403 error when iterate jira issues

---

_releases/ocp-4.15-test-jobs-amd64.json

cover upgrade path b/w patch releases for 4.15 nightly, for nightly we need 2 jobs to cover upgrade path b/w minor and patch releases

OCPERT-4 cover upgrade b/w patch releases for 4.15

---

oar/core/notification.py
tests/test_notification.py

Could you please review the changes?

OCPERT-9 Cache slack user/group IDs in runtime

---

prow/job/controller.py

fix issue when update same file multiple times, add default value `None` for `pop` func
```
File "/Users/rio.liu/coderepo/release-tests/prow/job/controller.py", line 923, in update_retried_job_run
TestResultAggregator(arch).update_retried_job_run(
File "/Users/rio.liu/coderepo/release-tests/prow/job/controller.py", line 862, in update_retried_job_run
json_data.pop("aggregated")
KeyError: 'aggregated'
```

OCPERT-26 fix keyerror when remove attr from dict

---

prow/job/controller.py

```
jobctl trigger-jobs-for-build --help
Usage: jobctl trigger-jobs-for-build [OPTIONS]
Options:
--build TEXT                    build version e.g. 4.16.20  [required]
--arch [amd64|arm64|multi|ppc64le|s390x]
architecture used to filter accepted build
--help                          Show this message and exit.
```
negative case build not found
```
jobctl trigger-jobs-for-build --build 4.15.80
2024-12-06T14:31:57Z: INFO: Initializing test job registry ...
2024-12-06T14:31:59Z: INFO: Test job definitions for 4.12-amd64 is initialized
2024-12-06T14:31:59Z: INFO: Test job definitions for 4.13-amd64 is initialized
2024-12-06T14:32:00Z: INFO: Test job definitions for 4.14-amd64 is initialized
2024-12-06T14:32:01Z: INFO: Test job definitions for 4.15-amd64 is initialized
2024-12-06T14:32:01Z: …
```

OCPERT-31 add new cmd to trigger jobs manually

---

tools/auto_release_test_dashboard.py

https://issues.redhat.com/browse/OCPERT-6

OCPERT-6: Enable 4.17 release in Test Results Dashboard

---

prow/job/sippy.py
tests/test_sippy.py

- support new param `view` e.g. `4.18-main`, it's shortcut of query parameters
- update test case

support new param view for component readiness

---

prow/job/controller.py
prow/job/job.py

- enable retry for func `get_job_results()` in Gangway API client
- handle the empty value in controller, if retry is still failed
- format code by black formatter

OCPERT-43 Handle 503 service unavailable error from Gangway server

---

prow/Dockerfile

new base image is based on python3.12-alpine, it has better performance and smaller size

Update base image to py3.12-alpine

---

prow/Dockerfile

/bin/bash is missed in alpine image

Install bash in dockerfile

---

prow/job/artifacts.py

upgraded python runtime to 3.12, there are few syntax warning from regex expression
```
/usr/src/release-tests/prow/job/artifacts.py:25: SyntaxWarning: invalid escape sequence '\/'
patterns = ['.*\/junit.*import-.*xml',
/usr/src/release-tests/prow/job/artifacts.py:26: SyntaxWarning: invalid escape sequence '\/'
'.*\/junit.*TEST-features-.*xml',
/usr/src/release-tests/prow/job/artifacts.py:27: SyntaxWarning: invalid escape sequence '\/'
'.*\/gui_test.*console-cypress.xml']
```

fix syntax warning in py3.12

---

prow/job/controller.py

perviously if 404 status code returned, UnknownObjectException will be returned, from yesterday the client raised GithubException, we need to check the status code in this exception to make sure file exists or not

OCPERT-46 fix issue for new exception behavior from github client api

---

prow/job/controller.py

fix issue mentioned in https://issues.redhat.com/browse/OCPERT-55

OCPERT-55 keep the job data as it is if error returned from gangway api

---

_releases/ocp-4.18-test-jobs-amd64.json
tools/auto_release_test_dashboard.py

https://issues.redhat.com/browse/OCPERT-47
depends on https://github.com/openshift/release/pull/61246

OCPERT-47 Enable auto release jobs for 4.18

---

oar/core/advisory.py

get assembly from release version for elliott cmd, this cmd is used by `check-cve-tracker-bug`

OCPERT-62 support candidate build for elliott

---

oar/core/util.py

DeprecationWarning: Function 'semver.parse_version_info' is deprecated. Deprecated since version 2.10.0.  This function will be removed in semver 3. Use 'semver.version.Version.parse' instead

replace deprecated func

---

oar/core/advisory.py
tests/test_advisory.py

```console
$ py -m unittest tests.test_advisory.TestAdvisoryManager.test_kernel_tag
No RHCOS nvr found, skip kernel tag checking
.
----------------------------------------------------------------------
Ran 1 test in 39.410s
OK
```

OCPERT-44 skip kernel tag checking if no rhcos nvr found in advisory builds

---

oar/core/notification.py
tests/test_notification.py

python -m unittest tests.test_notification.TestNotificationManager.test_get_qe_release_slack
...
2025-03-12 09:51:48,590 - DEBUG - Slack group id of 4.13-qe-leads is added to runtime cache
.
----------------------------------------------------------------------
Ran 1 test in 5.114s
OK

OCPERT-69 Send notification of unhealthy container to ERT member instead of artist

---

oar/core/advisory.py
oar/core/configstore.py
oar/core/jira.py
oar/core/worksheet.py

[OAR Fix wrong data types in docstring](https://issues.redhat.com/browse/OCPERT-56) in https://github.com/openshift/release-tests repository.
Details:
OAR tool docstring use wrong data types in docstring. For example [] instead of list.
Update all docstrings in OAR tool to use correct OAR types.
Scope:
OAR tool only.
It is not a goal to provide new docstrings, or add types to actual code.

OCPERT-56 OAR Fix wrong data types in docstring

---

prow/job/controller.py

handle exception case, aborted job does not have job url in Gangway API response

OCPERT-76 check job url is none for getting test result summary

---

_releases/ocp-4.14-test-jobs-amd64.json
_releases/ocp-4.15-test-jobs-amd64.json
_releases/ocp-4.16-test-jobs-amd64.json
_releases/ocp-4.17-test-jobs-amd64.json
_releases/ocp-4.18-test-jobs-amd64.json
_releases/ocp-4.19-test-jobs-amd64.json

according to test results in past few weeks. the disruptive jobs are stable enough, so promote these jobs as blocking job

OCPERT-73 promote disruptive jobs as blocking job

---

oar/core/configstore.py
oar/core/shipment.py

- Improve `get_shipment_mrs()` to handle both single and multiple shipment cases
- Put `get_advisories()` method back, we still have advisories defined in assembly e.g. microshift  and rpm
- Implement `get_status()` for GitLab MRs to check current state
- Filter MRs to only include opened ones during initialization
- Add better error handling and logging for MR operations
latest data structure change can be found in https://github.com/openshift-eng/art-tools/pull/1546

OCPERT-80 Enhance shipment MR handling and add advisory support back 

---

oar/core/shipment.py
tests/test_shipment.py

- Change gitlab import to use specific Gitlab class import
- Remove unused imports (gitlab, re, time, PathAccessError)
- Rename private method `_get_jira_issue_line_number` to public `get_jira_issue_line_number`
- Update all references to the renamed method in core and tests
- Clean up imports and remove unused dependencies
The change makes the Jira issue line number method publicly accessible since it's useful beyond internal class usage, while improving code organization.

OCPERT-88 Refactor GitLab client and make jira_issue_line_number public

---

oar/core/util.py

- Import warnings module to handle warning messages
- Add filter to suppress SSL patching warning from pip_system_certs
- Maintain existing logging functionality while reducing noise from known warning

OCPERT-119 Add SSL warning suppression and import warnings module

---

oar/core/shipment.py
oar/core/util.py

- Correct GitLab client initialization by using direct `Gitlab` class import instead of `gitlab.Gitlab`
- Add SSL warning suppression for unverified requests in logging setup
- Reorganize imports in util.py for better readability

OCPERT-119 Fix GitLab client initialization and suppress SSL warnings

---

_releases/ocp-4.12-test-jobs-amd64.json

This was merged https://github.com/openshift/release/pull/63374 and we need to update the test matrix accordingly

remove min-permissions for gcp 4.12 auto release jobs

---

oar/core/configstore.py

In some cases, the `parent_assembly` variable is not defined which causes an exception like below.  Set the variable to a default.
```
File "/Users/pruan/workspace/github_repos/release-tests/oar/core/configstore.py", line 359, in _get_assembly_attr
if attr_val == None and parent_assembly:  # no key found, try to get it from parent assembly
^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'parent_assembly' where it is not associated with a value cannot access local variable 'parent_assembly' where it is not associated with a value
```

define variable parent_assembly to None

---

oar/core/notification.py

fix issue https://issues.redhat.com/browse/OCPERT-121?filter=-2
```
pruan@mac ~/workspace/github_repos/release-tests $ oar -r 4.19.0-rc.5 update-bug-list
2025-06-06T22:13:46Z: INFO: task [Bug to be verified] status is changed to [In Progress]
2025-06-06T22:14:25Z: INFO: found existing bug OCPBUGS-36859 in report, checking...
2025-06-06T22:14:26Z: INFO: bug status of OCPBUGS-36859 is not changed
2025-06-06T22:14:26Z: INFO: found existing bug OCPBUGS-56619 in report, checking...
2025-06-06T22:14:29Z: INFO: bug status of OCPBUGS-56619 is not changed
2025-06-06T22:14:29Z: INFO: found existing bug OCPBUGS-54487 in report, checking...
2025-06-06T22:14:30Z: INFO: bug status of OCPBUGS-54487 is not changed
2025-06-06T22:14:31Z: INFO: found existing bug OCPBUGS-56185 in report, checking... …
```

addresses OCPERT-121

---

tools/auto_release_test_dashboard.py

Enable auto release jobs for 4.20
JIRA: https://issues.redhat.com/browse/OCPERT-129

OCPERT-129 Enable 4.20 on test result dashboard

---

oar/cli/cmd_drop_bugs.py
oar/core/advisory.py
oar/core/jira.py
tests/test_jira.py

python -m unittest tests.test_jira.TestJiraManager.test_get_high_severity_and_can_drop_issues
jira issue OCPBUGS-n102 is cve tracker: True, it must be verified
jira issue OCPBUGS-n103 is cve tracker: True, it must be verified
jira issue OCPBUGS-n104 is cve tracker: True, it must be verified
jira issue OCPBUGS-n111 is cve tracker: True, it must be verified
jira issue OCPBUGS-n100 is critical: True or customer case: None, it should be verified
jira issue OCPBUGS-n101 is critical: True or customer case: None, it should be verified
jira issue OCPBUGS-n105 is critical: True or customer case: None, it should be verified
jira issue OCPBUGS-n106 is critical: True or customer case: None, it should be verified
jira issue OCPBUGS-n107 is critical: True or customer case: None, it should be verified …

[OCPERT-128]Introduce a new flag for drop bugs command to drop the non-CVE issues forcibly

---

oar/cli/cmd_drop_bugs.py
oar/cli/cmd_take_ownership.py
oar/cli/cmd_update_bug_list.py
oar/core/advisory.py
oar/core/configstore.py
oar/core/notification.py
oar/core/operators.py
oar/core/worksheet.py
tests/test_worksheet.py

Refactor core operations into operator classes, to make OAR v2 compatible with both AD and shipment data
- Introduce BugOperator and ReleaseOwnershipOperator to consolidate related operations
- Move bug dropping and ownership management logic into respective operator classes
- Update CLI commands to use new operator classes instead of direct ShipmentData usage
- Improve documentation for drop_bugs command regarding pre-merge verification
- Add handling for abnormal advisories in ownership updates
- Include new operators.py file for operator implementations
The changes centralize related operations into dedicated classes for better organization and maintainability while preserving existing functionality.

OCPERT-134 Make OAR v2 compatible with both errata advisory and shipment data

---

oar/core/worksheet.py
pyproject.toml
tests/test_worksheet.py

- Add support for partial text hyperlinks via linkable_text parameter
- Implement custom format runs for precise text styling
- Add comprehensive input validation and error handling
- Improve docstring with detailed examples and parameter explanations
- Fix RPM advisory link format in TestReport class
- Update version of gspread-formatting in pyproject.toml
The changes allow more flexible hyperlink formatting in worksheets, including:
- Linking only portions of display text
- Custom text formatting with format runs
- Better error handling for invalid inputs

OCPERT-133 Enhance worksheet link formatting with advanced options

---

oar/cli/cmd_image_consistency_check.py
oar/core/shipment.py
tests/test_shipment.py

Implement functionality to:
- Extract components from shipment YAML files
- Query Pyxis API for image freshness grades
- Determine current health status of container images
- Track healthy/unhealthy components count
- Add comment to MR with the image health summary
This helps monitor the component image health status of container images being shipped.

OCPERT-136 Add container image health check for shipment components

---

tests/test_jira_notificator.py
tools/jira_notificator.py

https://issues.redhat.com/browse/OCPERT-98
This PR introduces a JIRA notification tool that monitors issues in the ON_QA state and sends escalation notifications to the appropriate stakeholders in a defined sequence.
The notification flow is as follows:
1. **QA Contact** – If an issue remains in ON_QA for more than 24 weekday hours, a notification is sent to the assigned QA contact requesting verification.
2. **Second Reminder (QA Contact / Team Lead)** – If the issue is still unresolved after another 24 weekday hours, a second notification is sent to the QA contact (planned: escalation to the Team Lead), requesting verification or coordination with their team lead to reassign the issue.
3. **Manager** – After another 24 weekday hours without resolution, a notification is sent to the QA …

OCPERT-98 Add jira notificator

---

oar/core/jenkins.py

- Skip metadata advisory check for Konflux flow in call_stage_job()
- Use errata_numbers instead of metadata_ad for ERRATA_NUMBERS parameter
- Make metadata advisory optional in stage pipeline job for non-errata flows
- Improve comments to clarify flow-specific behaviors
These changes allow the Jenkins integration to properly support both traditional errata and Konflux-based release workflows.

OCPERT-134 Update Jenkins stage job logic to handle Konflux flow

---

oar/core/operators.py

Modify `NotificationOperator` to fetch merge requests using `_cs.get_shipment_mrs()` instead of `sd.get_merge_requests()` when handling Konflux flow notifications. This ensures consistency with the Konflux workflow by using the correct MR source.

Update notification operator to use shipment MRs from CS

---

oar/core/advisory.py
oar/core/operators.py
oar/core/util.py
tests/test_util.py

- Modify advisory status change logic to check payload metadata URL accessibility for Konflux releases
- Update approval operator to handle Konflux flow separately, only moving RPM advisory status when metadata URL is accessible
- Add utility function to check payload metadata URL accessibility
- Add tests for new utility functionality
- Clean up imports and add missing logging
The changes ensure we don't prematurely move advisories before the payload metadata URL is accessible for Konflux-based releases.

Implement Konflux flow support for advisory status changes

---

oar/core/git.py
tests/test_git.py

Add `__del__` method to automatically call cleanup() when `GitHelper` objects are garbage collected. This prevents resource leaks by ensuring temporary directories are removed even if `cleanup()` isn't explicitly called. Also update test branch reference and remove redundant tearDown method in tests.

OCPERT-112 Add destructor to GitHelper for automatic cleanup

---

oar/core/shipment.py

Update error logging to use `self._mr.get_id()` instead of `mr.merge_request_id` for consistency and to ensure correct MR identifier is displayed when processing fails during image health checks.

OCPERT-112 Fix MR ID logging in image health check error message

---

oar/core/shipment.py

When auto_merge is set to True for GitLab merge requests, automatically set the squash option to true as well. This ensures consistent behavior where auto-merged MRs always use squash merging for cleaner commit history.

OCPERT-112 Enable squash when auto-merge is enabled in GitLab MRs

---

oar/core/advisory.py

Include the `--permissive` option when running elliott to handle advisory operations more flexibly, allowing the command to succeed even when non-critical validation checks fail.

OCPERT-158 Add --permissive flag to elliott command in advisory manager

---

oar/core/advisory.py
oar/core/const.py
tests/test_advisory.py

Extend kernel build tag validation to include RHCOS advisories by:
- Adding AD_IMPETUS_RHCOS constant
- Modifying check_kernel_tag() to handle RHCOS impetus alongside image
- Updating test cases to include RHCOS advisory scenario
- Bumping test config version to 4.19.10
This ensures consistent kernel tag validation across both image and RHCOS advisory types.

OCPERT-112 Add RHCOS impetus support for kernel tag checks

---

docs/ASYNC_APPROVAL_IMPLEMENTATION.md
oar/core/operators.py

Modify async approval implementation to set `process.daemon=False`, allowing background metadata checker processes to complete cleanup and timeout handling after parent process exit on Unix/Linux systems. Update documentation to reflect this behavior change for the "SCHEDULED" return value.

OCPERT-162 Set daemon=False for background process to ensure cleanup completion

---

docs/ASYNC_APPROVAL_IMPLEMENTATION.md
oar/core/operators.py

Switch from multiprocessing.Process to `subprocess.Popen` with `start_new_session=True` to ensure true process independence and proper cleanup across all platforms. This prevents zombie processes and allows the background metadata checker to continue running after parent process termination, improving reliability of async approval operations.

OCPERT-162 Replace multiprocessing with subprocess for independent background process

---

oar/core/operators.py

Corrects a race condition where the parent process hangs, preventing it from sending immediate feedback to the Slack app. By redirecting the standard I/O streams of the grandchild process to /dev/null, we ensure it fully detaches, allowing the parent to exit gracefully and its output to be captured.
This change ensures that:
The Slack app receives a "scheduled" message promptly. The background task runs independently without blocking the main process. The final result is still delivered to Slack by the long-running background process.

OCPERT-162 Detach background processes for immediate feedback

---

oar/core/operators.py
tools/slack_message_receiver.py

Previously, the background metadata checker process had stdout/stderr redirected to DEVNULL, making debugging difficult. This change:
- Creates timestamped log files in a temporary directory
- Redirects both stdout and stderr to these log files
- Adds initial metadata to log files for traceability
- Updates logging to include the log file location
Additionally, updates Slack bot references from "QE" to "ERT" branding:
- Changes logger name from "QEReleaseBot" to "ERTReleaseBot"
- Updates username check from "qe-release-bot" to "ert-release-bot"
- Updates response message text to "I'm ERT release bot"

Redirect background process output to log files for debugging

---

oar/cli/cmd_check_cve_tracker_bug.py
oar/core/advisory.py
oar/core/shipment.py

- Convert CVE tracker bug objects to strings in log messages for better readability
- Fix variable references in advisory.py and shipment.py to use 'tracker' instead of 'id'
- This ensures correct bug tracking and clearer debug output when checking for missed CVE tracker bugs

OCPERT-167 improve CVE tracker bug logging and fix variable references
