- oar/cli/cmd_group.py
- oar/cli/cmd_update_bug_list.py
- oar/core/config_store.json
- oar/core/config_store.py
- oar/core/worksheet_mgr.py
- tests/test_worksheet_mgr.py
add implementation of command `update-bug-list`
command help
```
./cli -r 4.12.18 update-bug-list -h
Usage: cli update-bug-list [OPTIONS]
Update bug status listed in report, update existing bug status and append
new ON_QA bug
Options:
```
command output
```
./cli -r 4.12.18 update-bug-list
2023-05-22T16:37:27Z: INFO: task [Bug to be verified] status is changed to [In Progress]
2023-05-22T16:38:47Z: INFO: checking all bugs are verified
2023-05-22T16:38:48Z: INFO: result is: yes
2023-05-22T16:38:49Z: INFO: task [Bug to be verified] status is changed to [Pass]
```
```
./cli -r 4.10.60 update-bug-list
2023-05-22T16:55:34Z: INFO: task [Bug to be verified] status is changed to [In Progress]
2023-05-22T16:56:36Z: INFO: found existing bug OCPBUGS-7337 in …
```
> command update bug list

- _releases/required-jobs.json
Add jobs for 4.11,4.12, and 4.13 stable testing. 
@kuiwang02 @Xia-Zhao-rh Could you help have a review? Thanks!
> add jobs for 4.11,4.12 and 4.13

- oar/core/config_store.json
update spreadsheet ids for `4.13`, `4.12`, `4.11`
> update report template

- oar/core/config_store.json
- oar/core/notification_mgr.py
- pyproject.toml
- from address is missed
- add `slack_sdk` in toml for installation
> fix notification bug

- prow/README.md
- prow/job/job.py
As the title, update README and add a `payload` flag to support specific run.
```console
MacBook-Pro:release-tests jianzhang$ job run --help
Usage: job run [OPTIONS] JOB_NAME
Run a Prow job via API call.
Options:
--payload TEXT  specify a payload, if not, it will use the latest payload
from https://amd64.ocp.releases.ci.openshift.org/
--help          Show this message and exit.
```
> update job's README

- prow/README.md
- prow/job/job.py
> record job name and payload

- prow/job/job.py
As title,
```console
MacBook-Pro:~ jianzhang$ job run --upgrade_to quay.io/openshift-release-dev/ocp-release:4.11.0-assembly.art6883.3 periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-4.11-upgrade-from-stable-4.10-gcp-ipi-disconnected-private-p2-f14 
{'job_execution_type': '1', 'pod_spec_options': {'envs': {'RELEASE_IMAGE_TARGET': 'quay.io/openshift-release-dev/ocp-release:4.11.0-assembly.art6883.3'}}}
Returned job id: 773f7076-ecc0-433f-aae1-e4dd09bcdf25
periodic-ci-openshift-openshift-tests-private-release-4.11-amd64-nightly-4.11-upgrade-from-stable-4.10-gcp-ipi-disconnected-private-p2-f14 None 773f7076-ecc0-433f-aae1-e4dd09bcdf25 2023-06-07T04:09:33Z https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/period …
```
> support upgrade job

- prow/README.md
> update prow README

- oar/core/const.py
- oar/core/notification_mgr.py
- oar/core/worksheet_mgr.py
- if not on_qa bugs won't send notification
- add const jira status dropped
> if not on_qa bugs won't send notification

- prow/README.md
> Add Internal Server Error description

- prow/job/job.py
> fix a env var issue

- oar/core/jenkins_helper.py
got issue like below
```
oar -r 4.12.25 image-consistency-check -n 2269
2023-07-17T10:48:08Z: INFO: check image consistency check job status according  to job id:2269
2023-07-17T10:48:11Z: INFO: quay.io/openshift-release-dev/ocp-release:4.12.25-x86_64
2023-07-17T10:48:11Z: ERROR: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.comjob/image-consistency-check/2269 version is not [4.12.25], please provide correct job id
```
the regex expr to parse release version from pull spec has problem
```
oar -r 4.12.25 image-consistency-check -n 2269
2023-07-17T10:59:03Z: INFO: check image consistency check job status according  to job id:2269
2023-07-17T10:59:07Z: INFO: image-consistency-check job: 2269 status is: In Progress
```
> fix regex expression issue

- oar/core/notification_mgr.py
disable mail notification functionality
> disable mail notification

- oar/README.md
> initial version of CLI readme

- pyproject.toml
install elliott from latest code base. cmd `find-bugs:sweep` contains option `--cve-only`
> install elliott from git repo

- oar/core/advisory_mgr.py
add waived to valid status list
> remove pending from valid status list

- oar/core/jira_mgr.py
@rioliu-rh  please check it, thanks
when drop bugs met issue: 
File "/home/wewang/522/release-tests/oar/cli/cmd_drop_bugs.py", line 27, in drop_bugs
dropped_bugs, must_verify_bugs = am.drop_bugs()
File "/home/wewang/522/release-tests/oar/core/advisory_mgr.py", line 201, in drop_bugs
issue.is_critical_issue()
File "/home/wewang/522/release-tests/oar/core/jira_mgr.py", line 254, in is_critical_issue
release_blocker = self.get_release_blocker()
File "/home/wewang/522/release-tests/oar/core/jira_mgr.py", line 224, in get_release_blocker
return self._issue.fields.customfield_12319743.value
AttributeError: 'NoneType' object has no attribute 'value'
2023-07-24T13:22:00Z: INFO: task [Remove unverified ON_QA bugs] status is changed to [Fail]
2023-07-24T13:22:01Z: INFO: Overall status is updated to …
> Fix release bug check issue

- oar/cli/cmd_change_advisory_status.py
- oar/cli/cmd_drop_bugs.py
Hi @rioliu-rh  updated according our discussion before, please check it, thanks
> Update some tasks  status to pass before remove ad to REL PREP

- oar/core/advisory_mgr.py
> remove unused log entry

- oar/core/config_store.json
- oar/core/config_store.py
2023-07-25T15:38:18Z: INFO: task [Payload image is well signed] status is changed to [In Progress]
2023-07-25T15:38:23Z: INFO: found image digest: sha256:3ca57045e070978b38c36d4c98e188795a6cb4b128130f9c8d7a08b47c133aba
2023-07-25T15:38:23Z: INFO: Comparing digest from url: https://mirror.oxxxxhift.com/pub/openshift-v4/signatures/openshift/release/sha256=xxxxc98e188795a6cb4b128130f9c8d7a08b47c133aba/
2023-07-25T15:38:25Z: INFO: Signature check PASSED
2023-07-25T15:38:26Z: INFO: task [Payload image is well signed] status is changed to [Pass]
2023-07-25T15:38:35Z: INFO: Overall status is updated to Green
> Add related signature url  to configstore

- oar/core/worksheet_mgr.py
- pyproject.toml
refine update overall status logic, only update overall status to `Green` when no failed task and current overall status is `Red`
add missed dependency `lxml`
> refine update overall status logic

- oar/cli/cmd_check_cve_tracker_bug.py
- oar/core/worksheet_mgr.py
- tests/test_worksheet_mgr.py
append missed cve tracker bugs to test report.
> append missed cve tracker bugs

- Dockerfile
> Add Dockerfile for oar

- README.md
> Update READEME for auto merging test

- oar/core/jira_mgr.py
- tests/test_jira_mgr.py
support add comment for jira issue. 
requirement is when test report is ready. we can add report url as comment in ART ticket.
```console
Running tests (unittest): /Users/rio.liu/coderepo/release-tests/tests/test_jira_mgr.py::TestJiraManager::test_add_comment
Running tests: /Users/rio.liu/coderepo/release-tests/tests/test_jira_mgr.py::TestJiraManager::test_add_comment
./test_jira_mgr.py::TestJiraManager::test_add_comment Passed
Total number of tests expected to run: 1
Total number of tests run: 1
Total number of tests passed: 1
Total number of tests failed: 0
Total number of tests failed with errors: 0
Total number of tests skipped: 0
Finished running tests!
```
> add comment for jira issue

- oar/core/advisory_mgr.py
- tests/test_advisory_mgr.py
@rioliu-rh please check it, thanks
> Add doc and prodsec approval basic function

- prow/Dockerfile.k8sgpt
> add a Dockerfile for k8sgpt

- tools/slack_message_receiver.py
support exec oar command via slack
usage: @qe-release-bot oar -h
> add slack message receiver

- prow/Dockerfile.k8sgpt
Address https://github.com/openshift/release/pull/42096#issuecomment-1676599564
> address kubeconfig issue

- oar/core/advisory_mgr.py
- oar/core/notification_mgr.py
if the advisory is released, the state is like [REL_PREP/SHIPPED LIVE], it is not [QE], we should not send alert to ART, only check if the state is [NEW_FILES]
> OCPQE-16534 fix issue of advisory abnormal state check

- oar/cli/cmd_image_consistency_check.py
- oar/cli/cmd_stage_testing.py
- oar/core/jenkins_helper.py
@rioliu-rh please check it, thanks
update  the workflow  when execute image-consistency-check command as follow:
1. check if already has  a pending job, if so, will give warning info:
2. if no pending job, will trigger a new job, check the triggered job status
if it's pending, send queue item link to team:
else it's in progress, send job url to team:
the same workflow for Stage-Pipeline job
> OCPQE-16444 Add workflow when job is in queue

- oar/cli/cmd_drop_bugs.py
fix issue: local variable 'requested_doc_ads' referenced before assignment
> Fix variable issue

- prow/job/job.py
The hardcode 4.13 image doesn't support 4.14 new features, such as NatGateway. So, after this PR, the base image will be inferred based on the provided arm payload. As follows,
```console
MacBook-Pro:release-tests jianzhang$ job run --payload quay.io/openshift-release-dev/ocp-release:4.14.0-aarch64 periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-ingress-lbtype-nlb-f28-destructive
Use amd64 base image: quay.io/openshift-release-dev/ocp-release:4.14.0-x86_64
{'job_execution_type': '1', 'pod_spec_options': {'envs': {'RELEASE_IMAGE_LATEST': 'quay.io/openshift-release-dev/ocp-release:4.14.0-x86_64', 'RELEASE_IMAGE_ARM64_LATEST': 'quay.io/openshift-release-dev/ocp-release:4.14.0-aarch64'}}}
Returned job id: 379e071f-bdf0-48ef-8a22-130c98ae17ed …
```
> OCPQE-17600: infer the corresponding amd64 build based on the provided arm build

- prow/job/__init__.py
- prow/job/job.py
As title, I would like to follow the Python format suggest by https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-else-return.html
Test pass
```console
jiazha-mac:release-tests jiazha$ job run_z_stream_test
use JSON file: _releases/required-jobs.json
getting the latest payload of 4.9
The latest version of 4.9 is: 4.9.59
No update! since the recored version 4.9.59 >= the new version 4.9.59
getting the latest payload of 4.10
The latest version of 4.10 is: 4.10.67
No update! since the recored version 4.10.67 >= the new version 4.10.67
getting the latest payload of 4.11
The latest version of 4.11 is: 4.11.57
No update! since the recored version 4.11.57 >= the new version 4.11.57
getting the latest payload of 4.12
The latest version of 4.12 is: 4.12.47
No …
```
> update code format according to pylint

- Dockerfile
- oar/cli/cmd_image_signed_check.py
- pyproject.toml
…lease page.  For details, please refer https://issues.redhat.com/browse/OCPQE-19017
> OCPQE-19017 address corner case in which image digest is not displaying in the release page

- prow/job/controller.py
reformat the code with vscode extension: ms-python.black-formatter. so the code style is followed by PEP8
> reformat code to follow PEP8 style

- prow/job/controller.py
if attribute `aggregated` can be found in test result json payload and it's value is `true`, skip aggregating this file.
> OCPQE-19030 check if attribute aggregated exists or not

- prow/job/controller.py
- prow/job/job.py
- check if all required jobs are success
- check if there is no job definition found in `TestJobRegistry`
- fix return value is none issue
> OCPQE-19030 check if all required jobs are success, fix few none value issues

- prow/job/artifacts.py
- prow/job/sippy.py
- prow/setup.py
- tests/test_artifacts.py
- Get file list with naming pattern list
- List all QE test related junit xml files
- Parse junit file to generate test job summary
> OCPQE-20766 Implement module to interact with prow job artifacts

- prow/job/controller.py
add missed logic to calculate failed jobs
> OCPQE-22219 calculate failed job

- _releases/ocp-4.16-test-jobs-amd64.json
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-gcp-ipi-mini-perm-custom-type-f360/1793028979272192000
```console
{  ons/us-central1/addresses/ci-op-ty4g6xly-81474-7h7vn-cluster-ip', resourceInUseByAnotherResource
level=warning msg=failed to delete network ci-op-ty4g6xly-81474-7h7vn-network with error: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE: The network resource 'projects/XXXXXXXXXXXX/global/networks/ci-op-ty4g6xly-81474-7h7vn-network' is already being used by 'projects/XXXXXXXXXXXX/regions/us-central1/subnetworks/ci-op-ty4g6xly-81474-7h7vn-master-subnet'
level=warning msg=failed to delete subnetwork ci-op-ty4g6xly-81474-7h7vn-master-subnet: googleapi: Error 400: The …
```
> OCPQE-21399 disable gcp job due to resource conflict issue

- prow/job/artifacts.py
- prow/job/controller.py
- tests/test_artifacts.py
Changes from test result aggregator
- read e2e test report from artifacts openshift-e2e-test-qe-report/artifacts/test-results.yaml
- add it to job result json file
> OCPQE-22219 add openshift-e2e-test-qe-report to job result

- prow/job/job.py
observed 503 Service Unavailable error when trigger prow job in auto release pipeline, add retry support for post request here.
> add retry support for job api

- _releases/ocp-4.12-test-jobs-amd64.json
add test registry config for 4.12 nightly and stable
> OCPQE-22653 add test registry config for 4.12

- tools/slack_message_receiver.py
- combine stdout,stderr
- split message due to slack api limit
> split the message due to slack api limit

- prow/job/controller.py
details please refer to [OCPQE-23403](https://issues.redhat.com/browse/OCPQE-23403)
> OCPQE-23403 support nightly upgrade testing with upgrade-from-stable build

- oar/core/advisory_mgr.py
- oar/core/worksheet_mgr.py
- there are few parameters use deprecated type,replace `[]` with `list` 
- format code as well
> correct parameter type

- Dockerfile
- prow/Dockerfile
python3.11 has better performance than 3.10
> update base image to python:3.11

- tools/slack_message_receiver.py
- when we use slack bot to execute oar cmd with email address, slack will transform the email address with mailto format, we need to filter out the email and replace the mailto string in cmd.
- add audit log func to record username and cli received.
```console
INFO:TestSocketMode:received cmd from user <rioliu>: oar -h
```
> replace mailto expression and add audit log

- OWNERS
Could you please add me to the reviewers list?
> Add jhuttana to reviewers section

- _releases/ocp-4.16-test-jobs-amd64.json
Add aws DR tests to release job
> Add aws DR tests to release job

- _releases/ocp-4.16-test-jobs-arm64.json
Support arm64 platform release jobs
> Support arm64 platform release jobs

- oar/core/notification_mgr.py
User's email id in jira profile is not same as slack profile, e.g. jira email id contains `+jira`, we need to transform it to remove the substring, then the email id can be used to lookup slack user id
> transform email id that contains special chars

- prow/job/controller.py
Handle the case that only informing jobs are configured.
> refine condition of qe accepted

- oar/controller/detector.py
Fix error when release list is empty.
[OCPQE-24595](https://issues.redhat.com/browse/OCPQE-24595)
> OCPQE-24595 add check for empty release list

- oar/cli/cmd_create_test_report.py
- oar/core/exceptions.py
- oar/core/worksheet.py
```
$ oar -r 4.12.62 create-test-report
2024-08-09T18:46:55Z: INFO: test report of 4.12.62 already exists, url: xxx
```
> refine error handling for existing worksheet

- oar/controller/detector.py
we got a problem that z-stream release info is not updated timely in this repo by ART, the latest z-stream version is less than latest version from release stream 4-stable.
```
$ oarctl start-release-detector -r 4.15
2024-08-14T12:25:52Z: INFO: latest z-stream version: 4.15.26
2024-08-14T12:25:52Z: INFO: latest stable version: 4.15.27
2024-08-14T12:25:52Z: INFO: no new z-stream release found
```
> OCPQE-24474 compare patch versions

- tools/slack_message_receiver.py
feedback from user, it's better to send reply to the slack thread
> send reply to thread

- oar/core/advisory.py
- get secalert by refresh api 
- check if alerts object is empty
> OCPQE-25165 refresh secalert and check alerts is empty

- _releases/ocp-4.16-test-jobs-amd64.json
- _releases/ocp-4.16-test-jobs-arm64.json
Remove DR jobs of AWS platform and add new jobs for GCP platform.
>  Remove DR jobs of AWS platform and add jobs for GCP

- oar/README.md
Could you please review the changes?
> Refine oar README.md for change-advisory-status

- tools/auto_release_test_dashboard.py
- configure cache TTL with 3h
- add a button to clear cache by user
> support clearing cache manually

- tools/auto_release_test_dashboard.py
add 4.13 in select box, user can list 4.13 test results
> OCPQE-25316 add 4.13 to dashboard

- oar/README.md
- oar/core/advisory.py
- oar/core/configstore.py
- oar/core/notification.py
- oar/core/worksheet.py
https://issues.redhat.com/browse/OCPQE-25520
> OCPQE-25520 Update OAR comments and readme file

- prow/job/controller.py
- prow/job/job.py
Fix none type error in
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-tests-master-qe-release-gate-test/1834281592881680384/artifacts/qe-release-gate-test/release-qe-tests/build-log.txt
> fix none type error when getting job info

- oar/core/advisory.py
details please refer to https://issues.redhat.com/browse/OCPQE-26408
> OCPQE-26408 filter out microshift advisory

- OWNERS
- remove reviewer/approver which won't be involved in this project
- add approvers to cover PR approval in different timezones.
> clean up owners file

- oar/controller/detector.py
Parse and compare z-stream version and stable versions by package `semver`
> OCPERT-12 use semver to parse and compare versions

- _releases/ocp-4.15-test-jobs-amd64.json
Add test job registry config for 4.15
> OCPQE-26461 Add test job registry config for 4.15

- tools/auto_release_test_dashboard.py
Enable 4.15 on test result dashboard
> OCPQE-26461 Enable 4.15 on test result dashboard

- README.md
@rioliu-rh Could you please take look?
> Correct the typo

- catalog-info.yaml
> QC-132: add oar to backstage

- prow/job/controller.py
- add http retry handler for `JobController` and `TestResultAggregator`
- add `4.17` in valid release list
> OCPERT-16 add retry handler for job controller and test result aggregator

- prow/job/controller.py
- declare func at module level to create http session with refined retry strategy
- declare session variable in different classes and init them with module level function `create_session`
> OCPERT-16 refine retry strategy

- prow/job/controller.py
enable stream mode to handle `ChunkedEncodingError`
> OCPERT-16 enable streaming for response content processing

- prow/job/controller.py
add new cli cmd `promote-test-results` to promote the test result manually, if all failures are analyzed and there is no product issue, the test results are accepted.
```
$ jobctl promote-test-results --help
Usage: jobctl promote-test-results [OPTIONS]
Options:
--arch [amd64|arm64|multi|ppc64le|s390x]
architecture used to filter test result
--build TEXT                    build version e.g. 4.16.20  [required]
--help                          Show this message and exit.
```
it will add new attribute `manual_promotion` to the test result file, and update attribute `aggregated` to `false`, so aggregator will process this file in next job run. if `manual_promotion` is detected, release payload will be updated with qe accepted label
> OCPERT-25 support manual promotion for blocking test results

- tools/auto_release_test_dashboard.py
Show state as `Accepted (Manually Promoted)` if `manual_promotion` found in test result
> OCPERT-25 add new state for manually promoted build

- prow/job/controller.py
usage:
```console
$ jobctl update-retried-job-run --help
Usage: jobctl update-retried-job-run [OPTIONS]
Options:
--arch [amd64|arm64|multi|ppc64le|s390x]
architecture used to filter test result
--build TEXT                    build version e.g. 4.16.20  [required]
--job-name TEXT                 prow job name configured in test job
registry  [required]
--current-job-id TEXT           current job run id  [required]
--new-job-id TEXT               new job run id used to replace current job
id  [required]
--help                          Show this message and exit.
```
cmd example
```console
$ jobctl update-retried-job-run --build 4.15.0-0.nightly-2024-11-28-042237 --job-name periodic-ci-openshift-openshift-tests-private-release-4.15-automated-release-gcp-ipi-f999 --current-job-id …
```
> OCPERT-26 add new cmd update-retried-job-run

- tools/slack_message_receiver.py
enable streaming and increase value of `max_tokens`
model details xref: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3
> OCPERT-11 refine LLM client params

- prow/job/controller.py
refine the validation logic for required env vars. below is list of required env var for different `jobctl` commands
- start-controller: `GITHUB_TOKEN`, `APITOKEN`, `GCS_CRED_FILE`
- start-aggregator: `GITHUB_TOKEN`, `APITOKEN`, `GCS_CRED_FILE`
- update-retried-job-run: `GITHUB_TOKEN`
- promote-test-results: `GITHUB_TOKEN`
samples
```console
$ jobctl start-aggregator --arch amd64
Missing required environment variables: GITHUB_TOKEN, APITOKEN, GCS_CRED_FILE
$ jobctl promote-test-results --build 4.15.0-0.nightly-2024-12-03-031414
Missing required environment variables: GITHUB_TOKEN
```
> OCPERT-25 OCPERT-26 refine required env var validation

- oar/cli/cmd_image_consistency_check.py
- oar/core/advisory.py
- oar/core/notification.py
- oar/core/util.py
- tests/test_advisory_grade.py
https://issues.redhat.com/browse/OCPERT-13
> OCPERT-13 add check for advisory grades

- oar/core/advisory.py
temp w/a to handle INC3282265 - errata.devel.redhat.com certificate has expired, when errata cert is updated, rollback this change
> OCPERT-32 temp w/a to handle incident errata cert has expired

- oar/core/configstore.py
- oar/core/worksheet.py
- tests/test_configstore.py
support getting attr `release_jira` from basis assembly
fix issue create test report issue if `reference_releases` is empty
add new unit test
> OCPERT-35 get jira from basis assembly

- _releases/ocp-4.17-test-jobs-amd64.json
https://issues.redhat.com/browse/OCPERT-8
> OCPERT-8 Add test job registry config for 4.17

- prow/job/controller.py
- prow/job/job.py
the auto formatted code does not work on py3.11
> OCPERT-43 revert auto formatted code made by black formatter on runtime py3.12

- _releases/ocp-4.13-test-jobs-amd64.json
- _releases/ocp-4.14-test-jobs-amd64.json
- _releases/ocp-4.15-test-jobs-amd64.json
- _releases/ocp-4.16-test-jobs-amd64.json
- _releases/ocp-4.17-test-jobs-amd64.json
Rename jobs affected after PR https://github.com/openshift/release/pull/61201
> OCPERT-38 Rename jobs with fips enabled. Update affected jobs

- oar/core/advisory.py
- oar/core/jira.py
- oar/core/notification.py
- oar/core/worksheet.py
Fix wrong data types in docstring
https://issues.redhat.com/browse/OCPERT-56
> OCPERT-56. OAR Fix wrong data types in docstring

- oar/core/jira.py
- oar/core/worksheet.py
https://issues.redhat.com/browse/OCPERT-53
> OCPERT-53 Update QA contact and notify about empty QA contact

- oar/cli/cmd_change_advisory_status.py
- oar/core/advisory.py
- oar/core/const.py
- oar/core/jira.py
- tests/test_advisory.py
https://issues.redhat.com/browse/OCPERT-72
> OCPERT-72 Prevent changing status of advisory with unfinished jiras

- oar/core/jira.py
https://issues.redhat.com/browse/OCPERT-10
> OCPERT-10 Fix wrong issue data type

- oar/cli/cmd_take_ownership.py
- oar/core/exceptions.py
- oar/core/notification.py
- oar/core/shipment.py
- oar/core/util.py
- tests/test_notification.py
- tests/test_shipment.py
This PR adds GitLab server integration and email validation functionality to support QE release lead identification in shipment workflows.
- Added new exception classes (GitLabMergeRequestException, GitLabServerException, ShipmentDataException)
- Implemented GitLabServer class with email-to-username lookup capability
- Added email validation utility function with regex pattern
- Enhanced ShipmentData with QE release lead comment functionality
- Added comprehensive test coverage for new features
- Added unit tests covering all new functionality
- Includes both mock-based tests and optional real API test (when GITLAB_TOKEN is set)
- Verified email validation with various valid and invalid formats
> OCPERT-84 Enable QE release lead identification in shipment workflow

- oar/cli/cmd_update_bug_list.py
- oar/core/const.py
- oar/core/worksheet.py
- tests/test_worksheet.py
- replace advisory info with shipment info in test report
- get jira issues from shipment data instead of advisory
> OCPERT-85 OCPERT-100 Refactor codebase to replace advisory to shipment

- oar/core/worksheet.py
https://issues.redhat.com/browse/OCPERT-101
> OCPERT-101 Prevent accidental data truncation from string slicing

- oar/core/shipment.py
- Change `get_all_files()` to default to 'yaml' extension instead of optional
- Remove filename pattern check in NVR extraction and rely on jsonpath
- Update method docstrings to reflect changes
- Clean up YAML file processing logic in ShipmentData class
The changes simplify the code by making YAML the default file type and removing unnecessary filename validation, since we're already using jsonpath to safely extract NVRS from the YAML structure.
> OCPERT-80 Set YAML as default file extension and simplify NVR extraction

- .gitignore
- oar/cli/cmd_drop_bugs.py
- oar/core/shipment.py
- tests/test_shipment.py
This PR refactors bug dropping functionality and enhances GitLab MR handling:
- **ShipmentData Refactor**:
- Centralized bug dropping logic in ShipmentData class
- Improved error handling and debug logging for GitLab operations
- **GitLab MR Enhancements**:
- Added support for suggestion comments on merge requests
- Implemented file content caching for better performance
- Added Jira issue extraction capability
- **Other Improvements**:
- Added TODO note in cmd_drop_bugs.py regarding doc/prodsec team collaboration
- Updated related test cases
- Manual testing of bug dropping functionality
- Verified GitLab MR comment functionality
- Confirmed Jira issue extraction works as expected
> OCPERT-88 Refactor bug dropping logic and improve GitLab MR handling

- oar/core/worksheet.py
JIRA ticket: https://issues.redhat.com/browse/OCPERT-108
Could you please review the changes?
> [OCPERT-108] Make shipment MRs clickable in the test-report

- OWNERS
> Remove non ERT members from OWNERS file

- tests/test_jenkins.py
- Update ConfigStore version to 4.18.17 in test setup
- Refactor test_call_stage_job to use simplified method call and add assertions
- Add new test case test_call_image_consistency_job with assertions
- Improve test coverage for JenkinsHelper functionality
> Update Jenkins tests and add new test cases

- oar/core/notification.py
https://issues.redhat.com/browse/OCPERT-121
> fix issue for OCPERT-121

- oar/core/configstore.py
- oar/core/jenkins.py
- oar/core/shipment.py
- oar/core/util.py
- Improve ConfigStore.get_shipment_mrs() docstring and formatting
- Add MR ID handling in JenkinsHelper using ShipmentData
- Enhance GitLabMergeRequest with get_id() and is_opened() methods
- Move MR URL parsing to util.parse_mr_url() for reuse
- Update Jenkins image consistency check to use MR ID instead of errata numbers
These changes centralize MR handling logic and provide better status checking capabilities while updating the Jenkins integration to use shipment MR IDs.
> OCPERT-122 Refactor shipment MR handling and update Jenkins parameters

- oar/core/advisory.py
Print more information about the greenwave test-result for each image.
> more verbose print for greenwave test results

- OWNERS
- tests/test_ldap.py
https://issues.redhat.com/browse/OCPERT-130
> Remove ltroiano from reviewers

- _releases/ocp-4.20-test-jobs-amd64.json
Enable auto release jobs for 4.20
JIRA: https://issues.redhat.com/browse/OCPERT-129
> OCPERT-129 Add test job registry config for 4.20

- oar/cli/cmd_image_consistency_check.py
- oar/cli/cmd_stage_testing.py
- oar/core/exceptions.py
- oar/core/jenkins.py
- oar/core/operators.py
- refactor the code of jenkins related cmds
- rename the exception class for jenkins helper
- do code clean up for operator functions
> Refactor code structure for cli cmds i-c-c and stage-testing

- oar/cli/cmd_image_consistency_check.py
- oar/cli/cmd_stage_testing.py
- oar/core/operators.py
- Replace ShipmentData usage with new ImageHealthOperator in cmd_image_consistency_check.py
- Implement ImageHealthOperator to handle both Konflux and Errata flows
- Simplify health check logic by returning boolean status
- Maintain same functionality while improving code organization
The change centralizes image health checking logic into a single operator class that can handle different release flows automatically, making the code more maintainable and consistent.
> OCPERT-134 Refactor image health check to use unified operator

- oar/core/shipment.py
- Implement `is_prod_release_success()` and `get_prod_release_info()` methods in GitLabMergeRequest class
- Refactor release stage checking into generic `get_release_info()` method
- Add corresponding `is_prod_release_success()` to ShipmentData class
- Maintain consistent error handling and logging patterns with existing stage release checks
This extends the existing release tracking functionality to include production release status monitoring.
> Add prod release status checks to GitLab merge requests

- oar/cli/cmd_change_advisory_status.py
- oar/cli/cmd_drop_bugs.py
- oar/core/advisory.py
- oar/core/configstore.py
- oar/core/exceptions.py
- oar/core/git.py
- oar/core/jenkins.py
- oar/core/jira.py
- oar/core/notification.py
- oar/core/operators.py
- oar/core/shipment.py
- oar/core/worksheet.py
- pyproject.toml
- tests/test_git.py
- tests/test_notification.py
- tests/test_shipment.py
- Conditionally update task status only after successful advisory approval
- Simplify bug dropping to remove unverified non-CVE bugs only
- Create new MR to remove dropped bugs from shipment yamls
- Remove multi-MR support, only one MR is available for a release
- Add new git module for version control operations
- Update health status checks with improved error handling
- Remove high severity bug tracking as separate concern
- Add comprehensive test coverage for new functionality
> OCPERT-112 Refactor advisory status updates and bug dropping logic

- oar/core/operators.py
Ensure background metadata checker process can send notifications to the correct Slack thread by explicitly passing `OAR_SLACK_CHANNEL` and `OAR_SLACK_THREAD` environment variables if they exist. Previously these variables were only inherited implicitly, which could cause notifications to be sent to the wrong thread or channel when running in background processes. Added logging to track the environment variables being passed.
> OCPERT-166 explicitly pass Slack context to background process

- oar/core/notification.py
- oar/core/operators.py
Improve notification system to handle cases where log messages are unavailable:
- Added `LogCaptureHandler` class to centralize log capturing functionality
- Modified Slack thread notification to send summary message when logs are not available
- Maintains existing behavior of sending full logs when available
- Provides better user experience by ensuring notifications are sent even without detailed logs
This change ensures consistent notification delivery while maintaining backward compatibility with existing log-based notifications.
> OCPERT-166 enhance Slack notification handling with fallback summary

- oar/notificator/jira_notificator.py
https://issues.redhat.com/browse/OCPERT-168
Enhance error handling so that if any processing issue fails, the script continues processing all items, and then exits with an error at the end, allowing Prow to detect an issue and send a Slack notification.
Related to:
- https://github.com/openshift/release/pull/69637
> OCPERT-168 Improve Jira Notificator error handling

- oar/notificator/jira_notificator.py
- tests/test_jira_notificator.py
https://issues.redhat.com/browse/OCPERT-170
> OCPERT-170 Add label to Jiras which are more than 24 hours from manager notification
